version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        # patch and minor updates don't matter for libraries; consumers will build
        # with their own lockfile. we just want major updates.
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
